name: Schenngerg
favicon: null
layout_spectrum: 0.7987705767154694
typography_spectrum: 0.7939513169694692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.05373779055662453
  lightness: 0.9017611369490623
  saturation: 0.5430649579502642
  rhythmicContrast: 0.6253375275991857
purpose: []
